name: Python Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      # Run flake8 (Style and Quality Check) - Fail only on major issues
      - name: Run flake8
        run: |
          flake8 --max-line-length=150 --select=W291 .
          

      # Run black (Code formatting check) - Fail if not formatted correctly
      - name: Run black (check mode)
        run: |
          black --check .
